// mac_hooks_internal.h — shared internals for the mac_hooks_* units.

// Generated by the mac_hooks.m split.  Holds the original preamble,

// every top-level type / #define / `static inline` helper (guard-

// wrapped), plus extern declarations so any part can reference another

// part's symbols under the same conditions as in the single file.

#ifndef MAC_HOOKS_INTERNAL_H
#define MAC_HOOKS_INTERNAL_H

#include <stdio.h>
#include <stdarg.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

// These macOS code-signing entry points are present in the iPadOS shared
// cache and used by Ventura's CoreLocationAgent, but the iPhoneOS SDK omits
// their declarations. Keep the declarations local instead of building this
// iOS-targeted interposer against macOS Security headers.
typedef struct __SecRequirement *SecRequirementRef;
typedef uint32_t SecCSFlags;
extern OSStatus SecRequirementCreateWithString(
    CFStringRef text, SecCSFlags flags, SecRequirementRef *requirement);
extern OSStatus SecRequirementCreateWithData(
    CFDataRef data, SecCSFlags flags, SecRequirementRef *requirement);

extern void macws_install_fsnode_root_volume_repair(void);
extern void macws_install_lsd_session_store_isolation(void);
static const char *macws_private_bootstrap_service_name(const char *name);
extern BOOL macws_macho_uuid_matches(const struct mach_header_64 *header,
                                     const uint8_t expected[16]);
static void macws_schedule_maps_location_capability_adapter(void);

// Expensive observation must never ride along with the normal interactive
// path. The launcher creates this sentinel before process start only when the
// operator explicitly passes --diagnostics, so cache the answer once and keep
// every production hot path to a single predictable branch.
static bool macws_runtime_diagnostics_enabled(void) {
    static _Atomic int cached = -1;
    int value = atomic_load_explicit(&cached, memory_order_acquire);
    if (value < 0) {
        value = getenv("MACWS_RUNTIME_DIAGNOSTICS") != NULL ||
            getenv("MACWS_FILECACHE_DIAG") != NULL ||
            access("/tmp/macws_runtime_diagnostics", F_OK) == 0 ||
            access("/tmp/macws_submit_diag", F_OK) == 0 ||
            access("/tmp/macws_submit_ring", F_OK) == 0 ||
            access("/tmp/macws_submit_fast_ring", F_OK) == 0 ||
            access("/tmp/macws_iogpu_error_diag", F_OK) == 0 ||
            access("/tmp/macws_command_error_diag", F_OK) == 0 ||
            access("/tmp/macws_queue_qos_diag", F_OK) == 0 ||
            access("/tmp/macws_kcmd_field_a4_diag", F_OK) == 0 ||
            access("/tmp/macws_kcmd_field_5e3_diag", F_OK) == 0 ||
            access("/tmp/macws_kcmd_field_6bc_diag", F_OK) == 0;
        atomic_store_explicit(&cached, value, memory_order_release);
    }
    return value != 0;
}

// libmachook is inherited by every chroot application, including shells
// launched by Terminal. Its historical "####" traces therefore appeared as
// command output and also added synchronous stderr I/O to production startup.
// Keep the instrumentation available behind the existing diagnostics switch,
// while leaving non-stderr file output untouched.
static int macws_filtered_fprintf(FILE *stream, const char *format, ...)
    __attribute__((format(printf, 2, 3)));
static int macws_filtered_fprintf(FILE *stream, const char *format, ...) {
    if (stream == stderr && !macws_runtime_diagnostics_enabled()) return 0;
    va_list args;
    va_start(args, format);
    int result = vfprintf(stream, format, args);
    va_end(args);
    return result;
}
#define fprintf macws_filtered_fprintf

// Diagnostic sentinels are a process-start contract.  macos_gui.sh creates or
// removes them before launch, and production_preflight rejects any survivor.
// Never stat them from the IOGPU submit/completion hot path: a production
// sample of VS Code's 60,000-fish GPU process caught 39 access(2) calls at the
// top of stack in six seconds.  Keep the individual gates (rather than folding
// them into the broad runtime-diagnostics bit) so diagnostic runs retain their
// existing selectivity.
#define MACWS_DEFINE_STARTUP_FLAG(function_name, path_literal) \
    static bool function_name(void) { \
        static _Atomic int cached = -1; \
        int value = atomic_load_explicit(&cached, memory_order_acquire); \
        if (value < 0) { \
            value = access(path_literal, F_OK) == 0; \
            atomic_store_explicit(&cached, value, memory_order_release); \
        } \
        return value != 0; \
    }

MACWS_DEFINE_STARTUP_FLAG(macws_res_diag_enabled,
                          "/tmp/macws_res_diag")
MACWS_DEFINE_STARTUP_FLAG(macws_iogpu_error_diag_enabled,
                          "/tmp/macws_iogpu_error_diag")
MACWS_DEFINE_STARTUP_FLAG(macws_submit_diag_enabled,
                          "/tmp/macws_submit_diag")
MACWS_DEFINE_STARTUP_FLAG(macws_submit_ring_enabled,
                          "/tmp/macws_submit_ring")
MACWS_DEFINE_STARTUP_FLAG(macws_queue_qos_diag_enabled,
                          "/tmp/macws_queue_qos_diag")
MACWS_DEFINE_STARTUP_FLAG(macws_kcmd_field_a4_diag_enabled,
                          "/tmp/macws_kcmd_field_a4_diag")
MACWS_DEFINE_STARTUP_FLAG(macws_kcmd_field_5e3_diag_enabled,
                          "/tmp/macws_kcmd_field_5e3_diag")
MACWS_DEFINE_STARTUP_FLAG(macws_kcmd_field_6bc_diag_enabled,
                          "/tmp/macws_kcmd_field_6bc_diag")

#undef MACWS_DEFINE_STARTUP_FLAG

// --- shared types / helpers (guard-wrapped) ---
typedef struct __SecRequirement *SecRequirementRef;

typedef uint32_t SecCSFlags;

#define fprintf macws_filtered_fprintf

#define MACWS_DEFINE_STARTUP_FLAG(function_name, path_literal) \
    static bool function_name(void) { \
        static _Atomic int cached = -1; \
        int value = atomic_load_explicit(&cached, memory_order_acquire); \
        if (value < 0) { \
            value = access(path_literal, F_OK) == 0; \
            atomic_store_explicit(&cached, value, memory_order_release); \
        } \
        return value != 0; \
    }

typedef struct {
    uintptr_t base;
    size_t size;
} MacWSJITRange;

#define MACWS_JIT_DIRTY_PAGE_CAPACITY 65536u

typedef CGRect (*macws_msg_rect_t)(id, SEL);

typedef id (*macws_msg_id_t)(id, SEL);

typedef id (*macws_msg_id_rect_t)(id, SEL, CGRect);

typedef id (*macws_msg_id_index_t)(id, SEL, NSUInteger);

typedef BOOL (*macws_msg_bool_id_t)(id, SEL, id);

typedef NSInteger (*macws_msg_integer_t)(id, SEL);

typedef NSUInteger (*macws_msg_count_t)(id, SEL);

typedef void (*macws_msg_void_bool_t)(id, SEL, BOOL);

typedef void (*macws_msg_void_uint_t)(id, SEL, NSUInteger);

typedef void (*macws_msg_void_view_order_t)(id, SEL, id, NSInteger, id);

typedef void (*macws_msg_void_rect_t)(id, SEL, CGRect);

typedef void *(*macws_agx_reserve_fn)(id, SEL, uint64_t);

typedef id IOSurfaceRef;

#if defined(LIBMACHOOK_ON_DEVICE_BUILD)
#define FORCE_M1_DRIVER 1
#endif

#define OFF_IOMobileFramebuffer_kern_SwapEnd_inputStructCnt 0x4400 + 0x24

#define OFF_IOMobileFramebuffer_kern_SwapEnd_submit 0x4400 + 0x30

#define OFF_SkyLight_CAWSManager_register_abort 0x18013c

#if FORCE_SW_RENDER
#define OFF_SkyLight_WSSystemCanCompositeWithMetal 0x53ae9028
#endif

#define OFF_Metal_MTLFragmentReflectionReader_deserialize_extra 0x90ebc + 0x16c

#define OFF_Metal_MTLInputStageReflectionReader_deserialize_extra 0x90678 + 0x3bc

#define OFF_QuartzCore_CABackingStore_force_accel 0x227cc

static inline uint64_t macws_ptr_blend(uint64_t addr, uint16_t div) {
    return (addr & 0x0000FFFFFFFFFFFFull) | ((uint64_t)div << 48);
}

#if __arm64e__
static inline uint64_t macws_pac_sign(uint64_t ptr, uint64_t mod, uint8_t key) {
    uint64_t r = ptr;
    switch (key) {
        case 0: asm("pacia %0, %1" : "+r"(r) : "r"(mod)); break;
        case 1: asm("pacib %0, %1" : "+r"(r) : "r"(mod)); break;
        case 2: asm("pacda %0, %1" : "+r"(r) : "r"(mod)); break;
        case 3: asm("pacdb %0, %1" : "+r"(r) : "r"(mod)); break;
    }
    return r;
}
#endif

#if !(__arm64e__)
static inline uint64_t macws_pac_sign(uint64_t ptr, uint64_t mod, uint8_t key) {
    return ptr;  // no PAC on plain arm64
}
#endif

typedef int (*PrepareForUse_t)(void *self, void *ctx, unsigned long long arg);

typedef int (*StartCompositeForDisplayStream_t)(void *self, id target0, id target1,
                                                 unsigned long load_action,
                                                 unsigned long store_action);

typedef int (*StartComposite_WSCD_t)(void *self, void *dest,
                                      unsigned long load_action,
                                      unsigned long store_action);

typedef int (*StartComposite_MTLTex_t)(void *self, id texture,
                                       unsigned long load_action,
                                       unsigned long store_action);

typedef void (*StateStack_pop_back_t)(void *deque);

typedef void (*EndCurrentComposite_t)(void *self, bool synchronize);

typedef void (*EndUpdate_t)(void *self, bool waitUntilSubmitted);

typedef void *(*WSCompositeDestinationCreateWithMetalTexture_t)(
    id texture, void *ctx, void *protectionOptions, void *colorspace, void *region);

typedef void (*MetalContext_StopCapture_t)(void *this);

typedef id (*MacWSUTTypeWithIdentifierFn)(id, SEL, NSString *);

typedef struct {
    char **values;
    size_t count;
    size_t capacity;
} MacWSCoreTypesIdentifierTable;

typedef void (*MacWSMKSetCanMonitorWiFiFn)(id, SEL, BOOL);

typedef void (*MacWSFileCacheFinalizeFn)(const void *cache);

typedef void *(*MacWSDesktopVolumeMapFindFn)(void *map, const void *key);

typedef bool (*MacWSSamePhysicalDeviceFn)(const void *lhs, const void *rhs);

#define MACWS_CRASH_BUF_LEN 16384

#define APPEND(...) do { \
        if (p < end) p += snprintf(p, (size_t)(end - p), __VA_ARGS__); \
    } while (0)

typedef int (*macws_abort_t)(uint32_t reason_namespace, uint64_t reason_code,
    void *payload, uint32_t payload_size, const char *reason_string,
    uint64_t reason_flags);

#define AP(...) do { if (p < end) p += snprintf(p, (size_t)(end - p), __VA_ARGS__); } while (0)

typedef void (*macws_agc_compile_t)(void *self, void *obj, void *module,
    uint64_t fastMath, uint64_t pipeType, void *opts, uint64_t safeMode);

typedef void (*macws_verify_t)(void *self);

typedef void (*MacWSVNCHandleMouse)(id, SEL, unsigned int, CGPoint, id);

typedef void (*MacWSVNCHandleKeyboard)(id, SEL, BOOL, unsigned int, id);

typedef void (*MacWSVNCSendKeyEvent)(id, SEL, unsigned short, BOOL, uint64_t);

typedef void (*MacWSVNCSetKeyModifiers)(id, SEL, uint64_t);

typedef enum {
    MacWSVNCInputModeStock = 0,
    MacWSVNCInputModeScaleOnly = 1,
    MacWSVNCInputModeHybrid = 2,
} MacWSVNCInputMode;

typedef void (*MacWSVNCRefreshCallback)(uint32_t, const CGRect *, void *);

typedef int (*MacWSRFBSendFramebufferUpdate)(void *, void *, void *);

typedef int (*MacWSVNCReadExact)(void *, void *, int);

typedef void (*MacWSVNCProcessNormalMessage)(void *);

enum {
    MacWSVNCDamageMagic = 0x564E444Du,
    MacWSVNCDamageMaxRectangles = 256,
};

typedef struct {
    uint32_t x;
    uint32_t y;
    uint32_t rectWidth;
    uint32_t rectHeight;
} MacWSVNCDamageRect;

typedef struct {
    uint32_t magic;
    uint32_t width;
    uint32_t height;
    uint32_t rectCount;
    uint64_t sequence;
    uint64_t changedPixels;
    uint32_t dirtyTileCount;
    uint32_t flags;
    MacWSVNCDamageRect rectangles[MacWSVNCDamageMaxRectangles];
} MacWSVNCDamageMessage;

typedef bool (*macws_os_feature_enabled_impl_fn)(const char *, const char *);

typedef boolean_t (*macws_dispatch_mig_callback_t)(
    mach_msg_header_t *request, mach_msg_header_t *reply);

typedef struct {
    CFURLRef appURL;
    CFArrayRef itemURLs;
    const void *passThruParams;
    uint32_t launchFlags;
    void *asyncRefCon;
} MacWSLSLaunchURLSpec;

#define CARENDER_ORIG "com.apple.CARenderServer"

#define CARENDER_NEW  "com.apple.macosbooter.CARenderServer"

#define FRONTBOARD_SYSTEM_ORIG "com.apple.frontboard.systemappservices"

#define FRONTBOARD_SYSTEM_NEW  "com.apple.macosbooter.frontboard.systemappservices"

#define VIEWBRIDGE_AUXILIARY_ORIG "com.apple.ViewBridgeAuxiliary"

#define VIEWBRIDGE_AUXILIARY_NEW  "com.apple.macosbooter.ViewBridgeAuxiliary"

#define EXTENSIONKIT_SERVICE_ORIG "com.apple.extensionkitservice"

#define EXTENSIONKIT_SERVICE_NEW  "com.apple.macosbooter.extensionkitservice"

#define HISERVICES_SERVICE_ORIG "com.apple.hiservices-xpcservice"

#define HISERVICES_SERVICE_NEW  "com.apple.macosbooter.hiservices-xpcservice"

#define DOCK_HELPER_SERVICE_ORIG "com.apple.dock.helper"

#define DOCK_HELPER_SERVICE_NEW  "com.apple.macosbooter.dock.helper"

#define GEOD_XPC_SERVICE "com.apple.geod"

#define GEOD_XPC_SERVICE_NEW "com.apple.macosbooter.geod"

#define LOCATIOND_DESKTOP_AGENT_ORIG \
    "com.apple.locationd.desktop.agent"

#define LOCATIOND_DESKTOP_AGENT_NEW \
    "com.apple.macosbooter.locationd.desktop.agent"

#define LOCATIOND_DESKTOP_REGISTRATION_ORIG \
    "com.apple.locationd.desktop.registration"

#define LOCATIOND_DESKTOP_REGISTRATION_NEW \
    "com.apple.macosbooter.locationd.desktop.registration"

#define LOCATIOND_DESKTOP_SPI_ORIG \
    "com.apple.locationd.desktop.spi"

#define LOCATIOND_DESKTOP_SPI_NEW \
    "com.apple.macosbooter.locationd.desktop.spi"

#define LOCATIOND_DESKTOP_SYNCHRONOUS_ORIG \
    "com.apple.locationd.desktop.synchronous"

#define LOCATIOND_DESKTOP_SYNCHRONOUS_NEW \
    "com.apple.macosbooter.locationd.desktop.synchronous"

#define LOCATIOND_SIMULATION_ORIG "com.apple.locationd.simulation"

#define LOCATIOND_SIMULATION_NEW \
    "com.apple.macosbooter.locationd.simulation"

typedef enum {
    MacWSIOSurfacePlaneWidth,
    MacWSIOSurfacePlaneHeight,
    MacWSIOSurfacePlaneCompressionType,
    MacWSIOSurfacePlaneHeightInCompressedTiles,
    MacWSIOSurfacePlaneWidthInCompressedTiles,
    MacWSIOSurfacePlaneBytesPerRow,
    MacWSIOSurfacePlaneBytesPerElement,
    MacWSIOSurfacePlaneElementWidth,
    MacWSIOSurfacePlaneElementHeight,
    MacWSIOSurfacePlaneSize,
    MacWSIOSurfacePlaneNumberOfComponents,
    MacWSIOSurfacePlaneBytesPerTileData,
    MacWSIOSurfacePlaneOffset,
    MacWSIOSurfacePlaneAddressFormat,
    MacWSIOSurfacePlanePropertyCount,
} MacWSIOSurfacePlaneProperty;

typedef struct {
    CFStringRef creationProperties;
    CFStringRef planeInfo;
    CFStringRef componentInfo;
    CFStringRef fullComponentInfo;
    CFStringRef shortKeys[MacWSIOSurfacePlanePropertyCount];
    CFStringRef fullKeys[MacWSIOSurfacePlanePropertyCount];
} MacWSIOSurfacePropertyKeys;

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_LIFE_CAP 16384u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_CPU_DUMP_CAP 64u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_CPU_DUMP_BYTES 0x10000u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_T82_REQUEST_CAP 512u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_T82_REQUEST_BYTES 0x100u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_SURFACE_DUMP_CAP 16u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_SURFACE_DUMP_BYTES 0x100000u
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_agx_life_entry {
    uint64_t gid;       // 0 = empty, UINT64_MAX = tombstone
    uint64_t gpu_address; // kernel-returned GPU VA (out+0x00)
    uint64_t data_bytes; // CPU mapping returned by GetDataBytes (out+0x08)
    uint64_t client_shared; // client-shared state returned from out+0x10
    uint64_t bytes;     // kernel-reported allocation size (out+0x48)
    uint64_t request_50; // translated request layout/arena word
    uint32_t client_id; // macOS client field (in+0x48), diagnostic only
    uint32_t surface_id;// type 0x82 IOSurface ID (translated in+0x30)
    uint32_t flags_14;  // translated request flags (in+0x14)
    uint8_t type;
};
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_LIFE_EVENT_CAP 4096u
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_agx_life_event {
    uint64_t serial;
    struct macws_agx_life_entry resource;
    uint8_t action; // 1=create, 2=destroy
};
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_agx_t82_request {
    uint64_t sequence;
    uint64_t life_event_serial;
    uint64_t gid;
    uint64_t gpu_address;
    uint32_t surface_id;
    uint16_t raw_length;
    uint16_t sent_length;
    unsigned char raw[MACWS_AGX_T82_REQUEST_BYTES];
    unsigned char sent[MACWS_AGX_T82_REQUEST_BYTES];
};
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_agx_surface_dump {
    struct macws_agx_life_entry resource;
    struct macws_agx_t82_request request;
    BOOL has_request;
};
#endif

#if defined(FORCE_M1_DRIVER)
typedef void *MacwsIOMobileFramebufferRef;
#endif

#if defined(FORCE_M1_DRIVER)
typedef void (*MacwsIOMFBFrameInfoCallback)(
    MacwsIOMobileFramebufferRef framebuffer, uint32_t swap_id,
    CFDictionaryRef info, void *context);
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_iomfb_frame_registration {
    MacwsIOMobileFramebufferRef framebuffer;
    io_connect_t client;
    MacwsIOMFBFrameInfoCallback callback;
    void *context;
    uint64_t last_presentation_time;
};
#endif

#if defined(FORCE_M1_DRIVER)
typedef void (*MacwsEnableFrameInfoTagListFunction)(
    void *server, const char *const *available_tags, size_t available_count,
    const char *const *requested_tags, size_t requested_count);
#endif

#if defined(FORCE_M1_DRIVER)
typedef uintptr_t (*MacwsIOMFBServerBeginSkylightUpdateFunction)(
    void *server, void *update);
#endif

#if defined(FORCE_M1_DRIVER)
typedef uintptr_t (*MacwsIOMFBServerFinishSkylightUpdateFunction)(
    void *server, void *update, uint32_t flags, uint64_t seed);
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_submit_diag_result {
    unsigned sequence;
    unsigned records;
    unsigned candidates;
    unsigned fixed;
};
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_SUBMIT_RING_COUNT 2048
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_SUBMIT_RING_MAX_BYTES 0x10000
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_submit_ring_entry {
    uint64_t serial;
    uint64_t life_event_serial;
    unsigned sequence;
    unsigned descriptor;
    unsigned fixed;
    uintptr_t descriptor_pointer;
    uintptr_t command_buffer;
    uintptr_t storage;
    size_t pre_commands_length;
    size_t pre_segments_length;
    size_t post_commands_length;
    size_t post_segments_length;
    unsigned char *pre_commands;
    unsigned char *pre_segments;
    unsigned char *post_commands;
    unsigned char *post_segments;
};
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_submit_ring_token {
    uint64_t serial;
    unsigned slot;
    int active;
};
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_SUBMIT_MARK_COUNT 32u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_KCMD_INSPECT_MAX 0x40000u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_SEGMENT_INSPECT_MAX 0x20000u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_FAST_SUBMIT_RING_COUNT 48u
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_FAST_SUBMIT_COMMAND_CAP MACWS_AGX_KCMD_INSPECT_MAX
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_FAST_SUBMIT_SEGMENT_CAP MACWS_AGX_SEGMENT_INSPECT_MAX
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_fast_submit_entry {
    _Atomic uint64_t guard;
    _Atomic uint64_t serial;
    _Atomic uintptr_t command_buffer;
    uint64_t life_event_serial;
    unsigned sequence;
    unsigned descriptor;
    _Atomic unsigned fixed;
    uintptr_t descriptor_pointer;
    uintptr_t storage;
    size_t commands_length;
    size_t commands_saved;
    size_t segments_length;
    size_t segments_saved;
    unsigned char commands[MACWS_FAST_SUBMIT_COMMAND_CAP];
    unsigned char segments[MACWS_FAST_SUBMIT_SEGMENT_CAP];
};
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_fast_submit_token {
    uint64_t serial;
    uint64_t life_event_serial;
    unsigned slot;
    unsigned sequence;
    unsigned descriptor;
    uintptr_t descriptor_pointer;
    uintptr_t command_buffer;
    uintptr_t storage;
    int active;
};
#endif

#if defined(FORCE_M1_DRIVER)
#define MACWS_AGX_SEGMENT_LIST_MAX_RECORDS 256u
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_iosurface_release_pair {
    io_connect_t connect;
    uintptr_t surface_id;
    BOOL armed;
};
#endif

#if defined(FORCE_M1_DRIVER)
typedef int32_t MacwsCVReturn;
#endif

#if defined(FORCE_M1_DRIVER)
typedef void *MacwsCVDisplayLinkRef;
#endif

#if defined(FORCE_M1_DRIVER)
typedef uint32_t MacwsCGDirectDisplayID;
#endif

#if defined(FORCE_M1_DRIVER)
typedef uint64_t MacwsCVOptionFlags;
#endif

#if defined(FORCE_M1_DRIVER)
typedef struct {
    uint32_t version;
    int32_t videoTimeScale;
    int64_t videoTime;
    uint64_t hostTime;
    double rateScalar;
    int64_t videoRefreshPeriod;
} MacwsCVTimeStampPrefix;
#endif

#if defined(FORCE_M1_DRIVER)
typedef MacwsCVReturn (*MacwsCVDisplayLinkOutputCallback)(
    MacwsCVDisplayLinkRef display_link,
    const MacwsCVTimeStampPrefix *now,
    const MacwsCVTimeStampPrefix *output_time,
    MacwsCVOptionFlags flags_in,
    MacwsCVOptionFlags *flags_out,
    void *user_info);
#endif

#if defined(FORCE_M1_DRIVER)
struct macws_cvdisplaylink_trace_slot {
    MacwsCVDisplayLinkRef display_link;
    MacwsCGDirectDisplayID requested_display_id;
    MacwsCVDisplayLinkOutputCallback callback;
    void *user_info;
    _Atomic unsigned long callback_count;
};
#endif

// --- original library extern declarations ---
extern IOSurfaceRef IOSurfaceCreate(NSDictionary* properties);

extern IOSurfaceRef IOSurfaceLookup(uint32_t surface_id);

extern CFDictionaryRef IOSurfaceCopyAllValues(IOSurfaceRef surface);

extern uint32_t IOSurfaceGetID(IOSurfaceRef surface);

extern size_t IOSurfaceGetWidth(IOSurfaceRef surface);

extern size_t IOSurfaceGetHeight(IOSurfaceRef surface);

extern size_t IOSurfaceGetAllocSize(IOSurfaceRef surface);

extern size_t IOSurfaceGetBytesPerRow(IOSurfaceRef surface);

extern size_t IOSurfaceGetBytesPerElement(IOSurfaceRef surface);

extern size_t IOSurfaceGetPlaneCount(IOSurfaceRef surface);

extern OSType IOSurfaceGetPixelFormat(IOSurfaceRef surface);

extern size_t IOSurfaceGetWidthOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetHeightOfPlane(IOSurfaceRef surface, size_t plane);

extern int IOSurfaceLock(IOSurfaceRef surface, uint32_t options, uint32_t *seed);

extern int IOSurfaceUnlock(IOSurfaceRef surface, uint32_t options, uint32_t *seed);

extern uint32_t IOSurfaceGetCompressionTypeOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetHeightInCompressedTilesOfPlane( IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetWidthInCompressedTilesOfPlane( IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetBytesPerRowOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetBytesPerElementOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetElementWidthOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetElementHeightOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetSizeOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetNumberOfComponentsOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetBytesPerTileDataOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t IOSurfaceGetOffsetOfPlane(IOSurfaceRef surface, size_t plane);

extern void *IOSurfaceGetBaseAddress(IOSurfaceRef surface);

extern void *IOSurfaceGetBaseAddressOfPlane(IOSurfaceRef surface, size_t plane);

extern uint32_t IOSurfaceGetAddressFormatOfPlane(IOSurfaceRef surface, size_t plane);

extern kern_return_t mach_vm_map( vm_map_t target_task, mach_vm_address_t *address, mach_vm_size_t size, mach_vm_offset_t mask, int flags, mach_port_t object, memory_object_offset_t offset, boolean_t copy, vm_prot_t cur_protection, vm_prot_t max_protection, vm_inherit_t inheritance);

extern au_asid_t audit_token_to_asid(audit_token_t atoken);

extern uid_t audit_token_to_auid(audit_token_t atoken);

extern kern_return_t mach_vm_read_overwrite( vm_map_t target_task, mach_vm_address_t address, mach_vm_size_t size, mach_vm_address_t data, mach_vm_size_t *outsize);

extern kern_return_t mach_vm_allocate( vm_map_t target, mach_vm_address_t *address, mach_vm_size_t size, int flags);

extern kern_return_t mach_vm_region( vm_map_t target_task, mach_vm_address_t *address, mach_vm_size_t *size, vm_region_flavor_t flavor, vm_region_info_t info, mach_msg_type_number_t *info_count, mach_port_t *object_name);

extern void MacWSInstallExtensionRuntimeCompatibility(void);

extern int gpu_bundle_find_trusted(const char *name, char *trusted_path, size_t trusted_path_len);

extern int __mac_syscall(const char *policy, int operation, void *argument);

extern int csr_get_active_config(uint32_t *configuration);

extern int sandbox_init_with_parameters(const char *profile, uint64_t flags, const char **params, char **errorbuf);

extern int sandbox_init(const char *profile, uint64_t flags, char **errorbuf);

extern mach_msg_return_t dispatch_mig_server( dispatch_source_t source, size_t max_message_size, macws_dispatch_mig_callback_t callback);

extern kern_return_t mach_vm_remap( vm_map_t target_task, mach_vm_address_t *target_address, mach_vm_size_t size, mach_vm_offset_t mask, int flags, vm_map_t source_task, mach_vm_address_t source_address, boolean_t copy, vm_prot_t *current_protection, vm_prot_t *maximum_protection, vm_inherit_t inheritance);

extern void macws_pthread_jit_write_protect_original(int enabled) __asm("_pthread_jit_write_protect_np");

extern int16_t LMGetBootDrive(void);

extern const CFStringRef _kCFURLVolumeRefNumKey;

extern Boolean _CFURLCopyResourcePropertyValuesAndFlags( CFURLRef url, uint64_t requestedValues, uint64_t *returnedValues, void *filePropertyValues, uint64_t requestedFlags, uint64_t *returnedFlags, CFErrorRef *error);

extern OSStatus LSOpenFromURLSpec(const MacWSLSLaunchURLSpec *launchSpec, CFURLRef *outLaunchedURL);

extern xpc_connection_t macws_xpc_connection_create_mach_service_raw( const char *, dispatch_queue_t, uint64_t) __asm("_xpc_connection_create_mach_service");

extern id objc_alloc(Class);

extern void *vproc_swap_string(void *vproc, int key, const char *input, char **output);

extern kern_return_t bootstrap_look_up(mach_port_t bp, const char *name, mach_port_t *sp);

extern kern_return_t bootstrap_check_in(mach_port_t bp, const char *name, mach_port_t *sp);

extern kern_return_t bootstrap_look_up2(mach_port_t bp, const char *name, mach_port_t *sp, pid_t target_pid, uint64_t flags);

extern kern_return_t bootstrap_look_up3(mach_port_t bp, const char *name, mach_port_t *sp, pid_t target_pid, const unsigned char instance[16], uint64_t flags);

extern kern_return_t bootstrap_check_in2(mach_port_t bp, const char *name, mach_port_t *sp, uint64_t flags);

extern kern_return_t bootstrap_check_in3(mach_port_t bp, const char *name, mach_port_t *sp, unsigned char instance[16], uint64_t flags);

extern xpc_connection_t macws_xpc_connection_create_mach_service_raw( const char *, dispatch_queue_t, uint64_t) __asm("_xpc_connection_create_mach_service");

extern xpc_connection_t macws_xpc_connection_create_listener_raw( const char *, dispatch_queue_t) __asm("_xpc_connection_create_listener");

extern void macws_xpc_main_raw(xpc_connection_handler_t handler) __asm("_xpc_main") __attribute__((noreturn));

#if defined(FORCE_M1_DRIVER)
extern uint32_t macws_get_current_iosurface_id(void);
#endif

#if defined(FORCE_M1_DRIVER)
extern uint32_t macws_get_current_iosurface_plane(void);
#endif

#if defined(FORCE_M1_DRIVER)
extern uint64_t macws_get_current_iosurface_compression_header_span(void);
#endif

#if defined(FORCE_M1_DRIVER)
extern uint32_t dyld_get_active_platform(void);
#endif

#if defined(FORCE_M1_DRIVER)
extern IOReturn IOMobileFramebufferSwapEnd(MacwsIOMobileFramebufferRef framebuffer);
#endif

#if defined(FORCE_M1_DRIVER)
extern IOReturn IOMobileFramebufferSwapCancel( MacwsIOMobileFramebufferRef framebuffer, uint32_t swap_id);
#endif

#if defined(FORCE_M1_DRIVER)
extern MacwsCVReturn CVDisplayLinkCreateWithCGDisplay( MacwsCGDirectDisplayID display_id, MacwsCVDisplayLinkRef *display_link_out);
#endif

#if defined(FORCE_M1_DRIVER)
extern MacwsCVReturn CVDisplayLinkSetOutputCallback( MacwsCVDisplayLinkRef display_link, MacwsCVDisplayLinkOutputCallback callback, void *user_info);
#endif

#if defined(FORCE_M1_DRIVER)
extern MacwsCGDirectDisplayID CVDisplayLinkGetCurrentCGDisplay( MacwsCVDisplayLinkRef display_link);
#endif

#if defined(FORCE_M1_DRIVER)
extern uint64_t CVGetCurrentHostTime(void);
#endif

// --- extern declarations (cross-part, guard-wrapped) ---
extern bool macws_jit_trace_enabled(void);

extern bool macws_kcmd_fix_enabled(void);

extern bool macws_kcmd_wrapped_fix_enabled(void);

extern bool macws_cancel_completion_enabled(void);

extern bool macws_real_swapend_diagnostic_enabled(void);

extern bool macws_jit_mprotect_compat_enabled(void);

extern bool macws_jit_fault_write_compat_enabled(void);

extern bool macws_jit_range_overlaps(uintptr_t base, size_t size);

extern void macws_jit_record_range(void *address, size_t size);

extern void macws_jit_remove_range(void *address, size_t size);

extern void macws_jit_restore_dirty_pages(void);

extern void macws_jit_ensure_exec_barrier_handler(void);

extern void macws_jit_set_all_permissions(int protection);

extern void macws_install_glass_blur_ab_if_requested(void);

extern void macws_repair_got_via_symtab(const struct mach_header_64 *header, intptr_t slide, const char *image_name);

extern bool macws_install_maps_location_capability_adapter(void);

extern void loadImageCallback(const struct mach_header* header, intptr_t vmaddr_slide);

extern int sysctlbyname_new(const char *name, void *oldp, size_t *oldlenp, void *newp, size_t newlen);

extern int __mac_syscall_new(const char *policy, int operation, void *argument);

extern int csr_get_active_config_new(uint32_t *configuration);

extern int sandbox_init_with_parameters_new(const char *profile, uint64_t flags, const char **params, char **errorbuf);

extern int sandbox_init_new(const char *profile, uint64_t flags, char **errorbuf);

extern kern_return_t mach_port_construct_new(ipc_space_t task, mach_port_options_ptr_t options, uint64_t context, mach_port_name_t *name);

extern mach_msg_return_t mach_msg_new(mach_msg_header_t *message, mach_msg_option_t option, mach_msg_size_t send_size, mach_msg_size_t receive_limit, mach_port_name_t receive_name, mach_msg_timeout_t timeout, mach_port_name_t notify);

extern mach_msg_return_t macws_dispatch_mig_server( dispatch_source_t source, size_t max_message_size, macws_dispatch_mig_callback_t callback);

extern au_asid_t audit_token_to_asid_new(audit_token_t atoken);

extern uid_t audit_token_to_auid_new(audit_token_t atoken);

extern int auditon_new(int cmd, void *data, uint32_t length);

extern int getaudit_addr_new(auditinfo_addr_t *auditinfo_addr, u_int length);

extern void *mmap_new(void *address, size_t size, int protection, int flags, int fd, off_t offset);

extern int mprotect_new(void *address, size_t size, int protection);

extern int munmap_new(void *address, size_t size);

extern kern_return_t mach_vm_remap_new( vm_map_t target_task, mach_vm_address_t *target_address, mach_vm_size_t size, mach_vm_offset_t mask, int flags, vm_map_t source_task, mach_vm_address_t source_address, boolean_t copy, vm_prot_t *current_protection, vm_prot_t *maximum_protection, vm_inherit_t inheritance);

extern void pthread_jit_write_protect_np_new(int enabled);

extern void macws_install_fsnode_root_volume_repair(void);

extern id objc_alloc_trace(Class cls);

extern void *vproc_swap_string_new(void *vproc, int key, const char *input, char **output);

extern size_t macws_confstr_new(int name, char *buffer, size_t length);

extern void macws_install_lsd_session_store_isolation(void);

extern kern_return_t bootstrap_look_up3_new(mach_port_t bp, const char *name, mach_port_t *sp, pid_t target_pid, const unsigned char instance[16], uint64_t flags);

extern kern_return_t bootstrap_check_in3_new(mach_port_t bp, const char *name, mach_port_t *sp, unsigned char instance[16], uint64_t flags);

extern void macws_xpc_main(xpc_connection_handler_t handler);

extern size_t macws_IOSurfaceGetWidthOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetHeightOfPlane(IOSurfaceRef surface, size_t plane);

extern uint32_t macws_IOSurfaceGetCompressionTypeOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetHeightInCompressedTilesOfPlane( IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetWidthInCompressedTilesOfPlane( IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetBytesPerRowOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetBytesPerElementOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetElementWidthOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetElementHeightOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetSizeOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetNumberOfComponentsOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetBytesPerTileDataOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetOffsetOfPlane(IOSurfaceRef surface, size_t plane);

extern void *macws_IOSurfaceGetBaseAddressOfPlane(IOSurfaceRef surface, size_t plane);

extern uint32_t macws_IOSurfaceGetAddressFormatOfPlane(IOSurfaceRef surface, size_t plane);

#if !defined(FORCE_M1_DRIVER)
extern kern_return_t IOServiceOpen_new(io_service_t service, task_port_t owningTask, uint32_t type, io_connect_t *connect);
#endif

extern void ModifyExecutableRegion(void *addr, size_t size, void(^callback)(void));

#if defined(FORCE_M1_DRIVER)
extern void macws_install_quartzcore_frame_info_hook( const struct mach_header *untyped_header);
#endif

#if defined(FORCE_M1_DRIVER)
extern void macws_install_quartzcore_coexist_pacing_hooks( const struct mach_header *untyped_header);
#endif

#if defined(FORCE_M1_DRIVER)
extern BOOL macws_macho_uuid_matches(const struct mach_header_64 *header, const uint8_t expected[16]);
#endif

#if defined(FORCE_M1_DRIVER)
extern IOReturn IOConnectCallMethod_new(io_connect_t client, uint32_t selector, const uint64_t *in, uint32_t inCnt, const void *inStruct, size_t inStructCnt, uint64_t *out, uint32_t *outCnt, void *outStruct, size_t *outStructCnt);
#endif

#if defined(FORCE_M1_DRIVER)
extern uint32_t macws_coexist_completion_pace_us(void);
#endif

#if defined(FORCE_M1_DRIVER)
extern uint32_t macws_coexist_activity_pace_us(uint32_t idle_pace_us);
#endif

#if defined(FORCE_M1_DRIVER)
extern uint32_t macws_coexist_wait_for_completion_slot(uint32_t interval_us);
#endif

#if defined(FORCE_M1_DRIVER)
extern IOReturn MacwsIOMobileFramebufferSwapEnd_new(void *framebuffer);
#endif

#if defined(FORCE_M1_DRIVER)
extern IOReturn IOConnectCallStructMethod_new(io_connect_t client, uint32_t selector, const void *inStruct, size_t inStructCnt, void *outStruct, size_t *outStructCnt);
#endif

#if defined(FORCE_M1_DRIVER)
extern kern_return_t IOServiceOpen_new(io_service_t service, task_port_t owningTask, uint32_t type, io_connect_t *connect);
#endif

extern _Atomic unsigned g_macws_jit_range_count;

extern pthread_mutex_t g_macws_jit_state_lock;

extern _Atomic unsigned g_macws_jit_active_writers;

extern _Thread_local bool g_macws_jit_thread_writable;

extern _Atomic unsigned g_macws_jit_remap_declines;

extern _Atomic unsigned g_macws_jit_mprotect_calls;

extern _Atomic unsigned g_macws_jit_handler_checks;

extern _Atomic bool g_macws_jit_needs_initial_rx;

extern _Atomic unsigned g_macws_jit_dirty_page_count;

extern _Atomic bool g_macws_jit_dirty_page_overflow;

extern void macws_jit_ensure_exec_barrier_handler(void);

extern void macws_jit_set_all_permissions(int protection);

extern _Thread_local uint64_t g_macws_agx_initfull_len;

extern _Atomic int g_macws_iomfb_coexist_swap_cancel;

extern void macws_install_quartzcore_frame_info_hook( const struct mach_header *header);

extern void macws_install_quartzcore_coexist_pacing_hooks( const struct mach_header *header);

extern uint32_t macws_coexist_completion_pace_us(void);

extern uint32_t macws_coexist_activity_pace_us(uint32_t idle_pace_us);

extern uint32_t macws_coexist_wait_for_completion_slot(uint32_t interval_us);

extern IOReturn (*g_macws_orig_iomfb_swap_end)(void *framebuffer);

extern IOReturn MacwsIOMobileFramebufferSwapEnd_new(void *framebuffer);

extern uint32_t macws_IOSurfaceGetCompressionTypeOfPlane( IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetWidthOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetHeightOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetHeightInCompressedTilesOfPlane( IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetWidthInCompressedTilesOfPlane( IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetBytesPerRowOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetBytesPerElementOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetElementWidthOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetElementHeightOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetSizeOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetNumberOfComponentsOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetBytesPerTileDataOfPlane(IOSurfaceRef surface, size_t plane);

extern size_t macws_IOSurfaceGetOffsetOfPlane(IOSurfaceRef surface, size_t plane);

extern void *macws_IOSurfaceGetBaseAddressOfPlane(IOSurfaceRef surface, size_t plane);

extern uint32_t macws_IOSurfaceGetAddressFormatOfPlane(IOSurfaceRef surface, size_t plane);

extern void EnableJIT(void);

extern int isJITEnabled(void);

extern void macws_xpc_main(xpc_connection_handler_t handler);

extern BOOL macws_macho_uuid_matches(const struct mach_header_64 *header, const uint8_t expected[16]);

extern void (*macws_orig_rfbGetFBRect)(int, int, int, int);

extern size_t (*macws_orig_CGDisplayPixelsWide)(uint32_t);

extern size_t (*macws_orig_CGDisplayPixelsHigh)(uint32_t);

extern BOOL (*macws_FSNode_isVolume_original)(id, SEL);

extern id (*macws_lsd_database_store_url_orig)(id, SEL);

extern id (*macws_lsd_database_store_url_uid_orig)(id, SEL, uid_t);

#if defined(FORCE_M1_DRIVER)
typedef struct { uint64_t clientID, iosResourceID, size; } macws_g_agxIdMap_t;
extern macws_g_agxIdMap_t g_agxIdMap[128];
#endif

#endif // MAC_HOOKS_INTERNAL_H
